#!/usr/bin/env bash
# This code prints fizz and buzz wherever it sees multiple of 3 and 5 respectively

i=1
while [ "$i" -le 100 ]; 
do 
  if (( i % 15 == 0 )); then 
    echo "FizzBuzz"
  elif (( i % 5 == 0 )); then
    echo "Buzz"
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  else
    echo "$i"
  fi
  i=$((i + 1))
done
