#!/usr/bin/env bash
# This code tells the story of etc/passwd

while IFS=":" read -r username password user_id group_id info home shell; do
  echo "The user $username is part of the $group_id gang, lives in $home directory and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd"
