#!/usr/bin/env bash
# This code prints bad luck and good luck for the 4th and 8th iterations respectively, istead of Best School 

i=1
while [ "$i" -le 10 ];
do
if [ "$i" -eq 4 ]; then
echo "bad luck"

elif [ "$i" -eq 8 ]; then 
echo "good luck"
else
echo "Best School"
fi
i=$((i + 1))
done
