#!/usr/bin/env bash
# Script that creates PID file and handles some signals

handle_sigterm() {
  echo "I hate the kill command"
  rm -f /var/run/myscript.pid  
  exit 0
}
handle_sigint() {
  echo "Y U no love me?!"
}
handle_sigquit() {
  rm -f /var/run/myscript.pid
  exit 0
}
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
  echo "4-to_infinity_and_beyond"
  sleep 2
done
