#!/usr/bin/env bash
# Script that creates PID file and handles some signals

PID_FILE="/tmp/myscript.pid"

handle_sigterm() {
  echo "I hate the kill command"
  rm -f "$PID_FILE"
  exit 0
}
handle_sigint() {
  echo "Y U no love me?!"
}
handle_sigquit() {
  rm -f "$PID_FILE"
  exit 0
}
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

echo $$ > "$PID_FILE"

while true; do
  echo "4-to_infinity_and_beyond"
  sleep 2
done
